spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848 # Nacos 服务地址
        username: nacos
        password: LZLlzl12345
      config:
        server-addr: localhost:18848
        namespace: public
        username: nacos
        password: LZLlzl12345
        file-extension: yaml
        group: DEFAULT_GROUP    # 也可以使用 group 分组不同环境配置
        refresh-enabled: true
    loadbalancer:
      retry:
        enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
  config:
    import: optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml?refreshEnabled=true




management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.nacos: DEBUG
    org.springframework.security: DEBUG