server:
  port: 9300

spring:
  application:
    name: ares-pay-center-service # 应用名称，用于服务注册
  profiles:
    active: dev
# 可以将更多自定义配置放入 Nacos 配置中心
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  # packages-to-scan: com.ares.cloud.gateway.web,com.ares.cloud.base.api,com.ares.cloud.payment.interfaces.web
  paths-to-match: /api/**

ares:
  oracle:
    wallet:
      enabled: true
      path: oracle/wallet
# SSL 配置
oracle:
  net:
    ssl_server_dn_match: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印 SQL 和参数
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ares.cloud.pay.infrastructure.persistence.entity